column_name_map:
  Cement (component 1)(kg in a m^3 mixture) : Cement
  Blast Furnace Slag (component 2)(kg in a m^3 mixture) : Furnace_Slag
  Fly Ash (component 3)(kg in a m^3 mixture): Fly_Ash
  Water  (component 4)(kg in a m^3 mixture) : Water
  Superplasticizer (component 5)(kg in a m^3 mixture): Superplasticizer
  Coarse Aggregate  (component 6)(kg in a m^3 mixture): Coarse_Aggregate
  Fine Aggregate (component 7)(kg in a m^3 mixture): Fine_Aggregate
  Age (day) : Age
  Concrete compressive strength(MPa, megapascals): Concrete_Compressive_Strength


columns:
  Cement: float
  Furnace_Slag: float
  Fly_Ash: float
  Water: float
  Superplasticizer: float
  Coarse_Aggregate: float
  Fine_Aggregate: float
  Age: float
  Concrete_Compressive_Strength: float

target_column: Concrete_Compressive_Strength


numerical_columns:
  - Cement
  - Furnace_Slag
  - Fly_Ash
  - Water
  - Superplasticizer
  - Coarse_Aggregate
  - Fine_Aggregate
  - Age



# categorical_columns:


columns_name_after_transformation:
  - Cement
  - Furnace_Slag
  - Fly_Ash
  - Water
  - Superplasticizer
  - Coarse_Aggregate
  - Fine_Aggregate
  - Age
  - Total_Aggregate
  - Concrete_Compressive_Strength